[workspace]
resolver = "3"
members = ["crates/mosaic_diagnostics", "crates/mosaic_grammar"]

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
must_use_candidate = "allow"
return_self_not_must_use = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
too_many_lines = "allow"
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
cast_lossless = "allow"
large_enum_variant = "allow"
cognitive_complexity = "allow"
manual_range_contains = "allow"
match_same_arms = "allow"
wildcard_imports = "allow"
unnecessary_wraps = "allow"
should_implement_trait = "allow"
